// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPOS.Data;

#nullable disable

namespace SmartPOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812115732_AddPackagingAndCaseReceiving")]
    partial class AddPackagingAndCaseReceiving
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartPOS.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SmartPOS.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Đồ uống"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Thực phẩm"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Đồ gia dụng"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Chăm sóc cá nhân"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Khác"
                        });
                });

            modelBuilder.Entity("SmartPOS.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SmartPOS.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "manager@smartpos.local",
                            EmployeeCode = "NV0001",
                            FullName = "Nguyễn Minh Anh",
                            IsActive = true,
                            PasswordHash = "DEVELOPMENT-ONLY-NOT-A-PASSWORD",
                            Phone = "0901000001",
                            Role = "Manager"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "cashier@smartpos.local",
                            EmployeeCode = "NV0002",
                            FullName = "Trần Quốc Bảo",
                            IsActive = true,
                            PasswordHash = "DEVELOPMENT-ONLY-NOT-A-PASSWORD",
                            Phone = "0901000002",
                            Role = "Cashier"
                        });
                });

            modelBuilder.Entity("SmartPOS.Models.FaceSample", b =>
                {
                    b.Property<int>("FaceSampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaceSampleId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FaceSampleId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("FaceSamples");
                });

            modelBuilder.Entity("SmartPOS.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartPOS.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SmartPOS.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CaseBarcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImportUnitName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Thùng");

                    b.Property<int>("MinStockAlert")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RetailUnitName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Cái");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitsPerImportUnit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ProductId");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CaseBarcode")
                        .IsUnique()
                        .HasFilter("[CaseBarcode] IS NOT NULL");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_CostPrice", "[CostPrice] >= 0");

                            t.HasCheckConstraint("CK_Product_MinStockAlert", "[MinStockAlert] >= 0");

                            t.HasCheckConstraint("CK_Product_SellingPrice", "[SellingPrice] >= 0");

                            t.HasCheckConstraint("CK_Product_StockQuantity", "[StockQuantity] >= 0");

                            t.HasCheckConstraint("CK_Product_UnitsPerImportUnit", "[UnitsPerImportUnit] >= 1");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8934588012221",
                            CaseBarcode = "18934588012228",
                            CategoryId = 1,
                            CostPrice = 4000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 10,
                            ProductName = "Nước suối Aquafina 500ml",
                            RetailUnitName = "Chai",
                            SellingPrice = 7000m,
                            StockQuantity = 48,
                            UnitsPerImportUnit = 24
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8934588012222",
                            CaseBarcode = "18934588012229",
                            CategoryId = 1,
                            CostPrice = 8000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 10,
                            ProductName = "Coca-Cola lon 330ml",
                            RetailUnitName = "Lon",
                            SellingPrice = 12000m,
                            StockQuantity = 36,
                            UnitsPerImportUnit = 24
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8934588012223",
                            CaseBarcode = "18934588012230",
                            CategoryId = 1,
                            CostPrice = 7000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 10,
                            ProductName = "Trà xanh C2 360ml",
                            RetailUnitName = "Chai",
                            SellingPrice = 11000m,
                            StockQuantity = 8,
                            UnitsPerImportUnit = 24
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8934588012224",
                            CaseBarcode = "18934588012231",
                            CategoryId = 2,
                            CostPrice = 3500m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 20,
                            ProductName = "Mì Hảo Hảo tôm chua cay",
                            RetailUnitName = "Gói",
                            SellingPrice = 5000m,
                            StockQuantity = 80,
                            UnitsPerImportUnit = 30
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8934588012225",
                            CategoryId = 2,
                            CostPrice = 9000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 8,
                            ProductName = "Bánh Oreo Original",
                            RetailUnitName = "Cái",
                            SellingPrice = 14000m,
                            StockQuantity = 25,
                            UnitsPerImportUnit = 1
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8934588012226",
                            CategoryId = 2,
                            CostPrice = 6500m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 12,
                            ProductName = "Sữa tươi Vinamilk 180ml",
                            RetailUnitName = "Cái",
                            SellingPrice = 9000m,
                            StockQuantity = 12,
                            UnitsPerImportUnit = 1
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8934588012227",
                            CategoryId = 3,
                            CostPrice = 18000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 6,
                            ProductName = "Khăn giấy rút Paseo",
                            RetailUnitName = "Cái",
                            SellingPrice = 25000m,
                            StockQuantity = 15,
                            UnitsPerImportUnit = 1
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8934588012228",
                            CategoryId = 3,
                            CostPrice = 24000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 8,
                            ProductName = "Nước rửa chén Sunlight 750g",
                            RetailUnitName = "Cái",
                            SellingPrice = 32000m,
                            StockQuantity = 5,
                            UnitsPerImportUnit = 1
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8934588012229",
                            CategoryId = 4,
                            CostPrice = 17000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 7,
                            ProductName = "Kem đánh răng P/S 180g",
                            RetailUnitName = "Cái",
                            SellingPrice = 24000m,
                            StockQuantity = 21,
                            UnitsPerImportUnit = 1
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8934588012230",
                            CategoryId = 4,
                            CostPrice = 42000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 5,
                            ProductName = "Dầu gội Clear Men 170ml",
                            RetailUnitName = "Cái",
                            SellingPrice = 55000m,
                            StockQuantity = 0,
                            UnitsPerImportUnit = 1
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8934588012231",
                            CategoryId = 5,
                            CostPrice = 28000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 5,
                            ProductName = "Pin AA Energizer vỉ 2",
                            RetailUnitName = "Cái",
                            SellingPrice = 38000m,
                            StockQuantity = 9,
                            UnitsPerImportUnit = 1
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8934588012232",
                            CategoryId = 5,
                            CostPrice = 12000m,
                            ImportUnitName = "Thùng",
                            MinStockAlert = 10,
                            ProductName = "Túi đựng rác tự hủy",
                            RetailUnitName = "Cái",
                            SellingPrice = 18000m,
                            StockQuantity = 30,
                            UnitsPerImportUnit = 1
                        });
                });

            modelBuilder.Entity("SmartPOS.Models.StockTransaction", b =>
                {
                    b.Property<int>("StockTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTransactionId"));

                    b.Property<string>("ImportUnitNameSnapshot")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ImportUnitQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("LooseUnitQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("UnitCostSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UnitsPerImportUnitSnapshot")
                        .HasColumnType("int");

                    b.HasKey("StockTransactionId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("SmartPOS.Models.Attendance", b =>
                {
                    b.HasOne("SmartPOS.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SmartPOS.Models.FaceSample", b =>
                {
                    b.HasOne("SmartPOS.Models.Employee", "Employee")
                        .WithMany("FaceSamples")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SmartPOS.Models.Order", b =>
                {
                    b.HasOne("SmartPOS.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SmartPOS.Models.OrderDetail", b =>
                {
                    b.HasOne("SmartPOS.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPOS.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartPOS.Models.Product", b =>
                {
                    b.HasOne("SmartPOS.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartPOS.Models.StockTransaction", b =>
                {
                    b.HasOne("SmartPOS.Models.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartPOS.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartPOS.Models.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("FaceSamples");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SmartPOS.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SmartPOS.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
